In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv('Data.csv')

In [12]:
dataset.head(5)
dataset.dtypes

No         int64
year       int64
month      int64
day        int64
hour       int64
pm2.5    float64
DEWP       int64
TEMP     float64
PRES     float64
cbwd      object
Iws      float64
Is         int64
Ir         int64
dtype: object

In [7]:
X = dataset.iloc[:, [1,2,3,4,6,7,8,9,10,11,12]].values
Y = dataset.iloc[:, 5].values

In [8]:
X

array([[2010, 1, 1, ..., 1.79, 0, 0],
       [2010, 1, 1, ..., 4.92, 0, 0],
       [2010, 1, 1, ..., 6.71, 0, 0],
       ..., 
       [2014, 12, 31, ..., 242.7, 0, 0],
       [2014, 12, 31, ..., 246.72, 0, 0],
       [2014, 12, 31, ..., 249.85, 0, 0]], dtype=object)

In [9]:
Y

array([ nan,  nan,  nan, ...,  10.,   8.,  12.])

In [22]:
#filling in missing data
from sklearn.preprocessing import Imputer
imputer = Imputer(missing_values = 'NaN', strategy= 'mean', axis = 0)
imputer = imputer.fit(Y)
Y = imputer.transform(Y)

C:\Users\Acer\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\Acer\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


In [30]:
Y

array([[ 129.,  148.,  159., ...,   10.,    8.,   12.]])